"""The command line every course's build.py exposes.

    python build.py              # Build both HTML and PDF
    python build.py --html       # HTML only (for quick previews)
    python build.py --pdf        # PDF only
    python build.py -v           # Verbose output
    python build.py --ci         # CI mode: keep stamped sources after the build
    python build.py --course-data   # only where the Site registers a generator

Build order: reconfigure the console for UTF-8, regenerate course data, find
the tools (before any source is touched), run the source passes, build, and
restore the sources unless `--ci`.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

from . import sources
from .html import build_html
from .pdf import build_pdfs
from .site import API_VERSION, BuildError, Site, Workspace
from .tools import MIN_TYPST, find_quarto, find_typst, install_hint, typst_version, version_tuple

COURSE_DATA_PLACEHOLDER = "# Generated by build.py --course-data; do not edit or commit\n"


def build_parser(site: Site) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=site.description)
    parser.add_argument("--html", action="store_true", help="Build HTML only")
    parser.add_argument("--pdf", action="store_true", help="Build PDF only")
    parser.add_argument("--ci", action="store_true",
                        help="CI mode: keep stamped sources (dates, resolved shortcodes) after the build")
    if site.course_data is not None:
        parser.add_argument("--course-data", action="store_true",
                            help="Only (re)generate _course-data.yml, then exit. Quarto runs "
                                 "this as a pre-render step so meta shortcodes resolve in preview.")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    return parser


def _reconfigure_streams() -> None:
    """UTF-8 out, always. Windows consoles default to a code page that cannot
    print Typst's error output, and the resulting `charmap` traceback used to
    hide the real error."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except (ValueError, OSError):
                pass


def _build_both(site: Site, quarto: Path, typst: Path, verbose: bool) -> bool:
    """PDFs first, stashed across the HTML render, which replaces _site/."""
    ok = True
    with tempfile.TemporaryDirectory() as tmp:
        tmp_pdf = Path(tmp)
        ok = build_pdfs(site, quarto, typst, verbose) and ok

        # Stash PDFs (preserving directory structure)
        pdf_files = list(site.site_dir.rglob("*.pdf")) if site.site_dir.exists() else []
        for pdf in pdf_files:
            rel = pdf.relative_to(site.site_dir)
            dest = tmp_pdf / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(pdf, dest)

        # Build HTML (this replaces _site/)
        ok = build_html(quarto, site.root, verbose) and ok

        # Restore PDFs into the site
        stashed = list(tmp_pdf.rglob("*.pdf"))
        for pdf in stashed:
            rel = pdf.relative_to(tmp_pdf)
            dest = site.site_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(pdf, dest)
        if stashed:
            print(f"  {len(stashed)} PDF(s) restored to _site/")
    return ok


def run(site: Site, argv: list[str] | None = None) -> int:
    """Build the site. Returns the process exit code."""
    _reconfigure_streams()

    if site.require_api != API_VERSION:
        print(f"ERROR: build.py was written for build core API {site.require_api}, "
              f"but the installed physicslabs extension provides API {API_VERSION}. "
              "Update build.py for the new core, or pin the extension release it was written for.")
        return 1

    args = build_parser(site).parse_args(argv)
    verbose = args.verbose

    if site.course_data is not None:
        # Derive course data first: a normal build needs it, and --course-data
        # is Quarto's pre-render entry point, which only wants the file.
        site.course_data(verbose)
        if not site.course_data_file.exists():
            # Quarto lists this file under metadata-files and fails if it is
            # missing, so leave a placeholder when there is nothing to derive.
            site.course_data_file.write_text(COURSE_DATA_PLACEHOLDER, encoding="utf-8")
        if getattr(args, "course_data", False):
            return 0

    # Default: build both
    build_both = not args.html and not args.pdf

    # Find the tools before touching any source.
    quarto = find_quarto()
    if quarto is None:
        print("ERROR: Quarto not found. Install from https://quarto.org/")
        return 1

    typst = None
    if args.pdf or build_both:
        typst = find_typst()
        if typst is None:
            print(f"ERROR: Typst 0.14+ not found. Install with: {install_hint()}")
            return 1
        version = typst_version(typst)
        if version and version_tuple(version) < MIN_TYPST:
            print(f"ERROR: Typst {version} found but 0.14+ is required for PDF/UA-1.")
            print(f"  Found at: {typst}")
            return 1
        print(f"Using Typst {version} at {typst}")

    # Source passes edit files in place. In local builds they are restored
    # after the build; with --ci the stamped content is kept for deployment.
    ws = Workspace(site.root)
    passes = site.source_passes if site.source_passes is not None else sources.DEFAULT_PASSES

    ok = True
    try:
        for source_pass in passes:
            source_pass(ws, verbose)

        if build_both:
            ok = _build_both(site, quarto, typst, verbose)
        else:
            if args.html:
                ok = build_html(quarto, site.root, verbose) and ok
            if args.pdf:
                ok = build_pdfs(site, quarto, typst, verbose) and ok
    except BuildError as exc:
        print(f"ERROR: {exc}")
        ok = False
    finally:
        if not args.ci:
            ws.restore()

    if ok:
        print("\nDone.")
        return 0
    print("\nBuild completed with errors.")
    return 1


main = run
