"""The command line and the build order, without running Quarto or Typst."""

from pathlib import Path

import pytest

from physicslabs_build import API_VERSION, BuildError, Site, cli, run


@pytest.fixture
def site(tmp_path: Path) -> Site:
    (tmp_path / "_quarto.yml").write_text("project:\n  type: physicslabs\n", encoding="utf-8")
    (tmp_path / "index.qmd").write_text('---\ntitle: "Home"\n---\n', encoding="utf-8")
    return Site(root=tmp_path, description="test site", require_api=API_VERSION)


def test_flags_match_the_course_scripts(site: Site):
    parser = cli.build_parser(site)
    args = parser.parse_args(["-v", "--ci"])
    assert (args.verbose, args.ci, args.html, args.pdf) == (True, True, False, False)
    assert not hasattr(args, "course_data")


def test_course_data_flag_exists_only_with_a_generator(site: Site):
    site.course_data = lambda verbose: None
    args = cli.build_parser(site).parse_args(["--course-data"])
    assert args.course_data


def test_api_mismatch_is_one_clear_line(site: Site, capsys):
    site.require_api = API_VERSION + 1
    assert run(site, []) == 1
    assert "build core API" in capsys.readouterr().out


def test_course_data_mode_writes_the_placeholder_and_exits(site: Site):
    calls = []
    site.course_data = lambda verbose: calls.append(verbose)
    assert run(site, ["--course-data"]) == 0
    assert calls == [False]
    assert site.course_data_file.read_text(encoding="utf-8").startswith("# Generated by build.py --course-data")


def test_course_data_mode_keeps_a_generated_file(site: Site):
    def generate(verbose):
        site.course_data_file.write_text("term: fall\n", encoding="utf-8")

    site.course_data = generate
    assert run(site, ["--course-data"]) == 0
    assert site.course_data_file.read_text(encoding="utf-8") == "term: fall\n"


def test_missing_quarto_fails_before_any_source_is_touched(site: Site, monkeypatch, capsys):
    touched = []
    site.source_passes = [lambda ws, verbose: touched.append(1)]
    monkeypatch.setattr(cli, "find_quarto", lambda: None)
    assert run(site, ["--html"]) == 1
    assert touched == []
    assert "Quarto not found" in capsys.readouterr().out


def test_a_failing_pass_restores_the_sources_and_exits_1(site: Site, monkeypatch, capsys):
    monkeypatch.setattr(cli, "find_quarto", lambda: Path("quarto"))
    page = site.root / "index.qmd"
    original = page.read_bytes()

    def stamp(ws, verbose):
        ws.write(page, "stamped\n")

    def fail(ws, verbose):
        raise BuildError("2 notebook(s) failed validation")

    site.source_passes = [stamp, fail]
    assert run(site, ["--html"]) == 1
    assert page.read_bytes() == original
    out = capsys.readouterr().out
    assert "ERROR: 2 notebook(s) failed validation" in out
    assert "Build completed with errors." in out


def test_ci_keeps_the_stamps(site: Site, monkeypatch):
    monkeypatch.setattr(cli, "find_quarto", lambda: Path("quarto"))
    monkeypatch.setattr(cli, "build_html", lambda quarto, root, verbose: True)
    page = site.root / "index.qmd"
    site.source_passes = [lambda ws, verbose: ws.write(page, "stamped\n")]
    assert run(site, ["--html", "--ci"]) == 0
    assert page.read_text(encoding="utf-8") == "stamped\n"


def test_local_build_restores_the_stamps(site: Site, monkeypatch):
    monkeypatch.setattr(cli, "find_quarto", lambda: Path("quarto"))
    monkeypatch.setattr(cli, "build_html", lambda quarto, root, verbose: True)
    page = site.root / "index.qmd"
    original = page.read_bytes()
    site.source_passes = [lambda ws, verbose: ws.write(page, "stamped\n")]
    assert run(site, ["--html"]) == 0
    assert page.read_bytes() == original
