"""Regenerate filters/logos.lua from the logo files in assets/img.

The chrome filter embeds the CU Boulder logos as data URIs so the header and
footer never depend on resource paths in the rendered site. Run this after
replacing a logo file.

Usage (from the repository root):
    python tools/gen-logos.py
"""

from __future__ import annotations

import base64
from pathlib import Path

LOGOS = [
    ("light", "cu-boulder-logo-text-black.svg", "image/svg+xml"),
    ("dark", "cu_boulder-white.svg", "image/svg+xml"),
    ("beboulder", "beboulder_white.png", "image/png"),
]


def main() -> int:
    here = Path(__file__).resolve().parents[1] / "_extensions" / "physicslabs"
    img_dir = here / "assets" / "img"
    lines = [
        "-- Generated by gen-logos.py from assets/img; do not edit by hand.",
        "return {",
    ]
    for key, filename, mime in LOGOS:
        data = (img_dir / filename).read_bytes()
        encoded = base64.b64encode(data).decode("ascii")
        lines.append(f'  {key} = "data:{mime};base64,{encoded}",')
    lines.append("}")
    out = here / "filters" / "logos.lua"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(here)} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
